#!/bin/bash

if [ -r /var/log/httpd/error_log ]; then
    multitail -x %f /var/log/httpd/error_log
fi

if [ -r /var/log/apache/error_log ]; then
    multitail -x %f /var/log/apache/error_log
fi

if [ -r /var/log/apache2/error_log ]; then
    multitail -x %f /var/log/apache2/error_log
fi
